kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-plus-as3-configmap
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.20.0",
        "id": "nginx-plus",
        "label": "CIS AS3 Example",
        "remark": "Example of using CIS",
        "AS3": {
          "class": "Tenant",
          "MyApps": {
             "class": "Application",
             "template": "generic",
             "ingress": {
                "class": "Service_TCP",
                "virtualAddresses": ["10.0.2.4"],
               "remark":"ingress: f5demo.tcp.v1",
               "virtualPort": 80,
                "pool": "ingress_pool"
             },
             "ingress_pool": {
                "class": "Pool",
                "monitors": [ "tcp" ],
                "members": [{
                   "servicePort": 80,
                   "serverAddresses": []
                }]
             }
            }
          }
        }
    }